stages:
  - build
  - retrain
  - deploy

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/username/aiops-quality-project:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/username/aiops-quality-project:$CI_COMMIT_SHA

retrain-model:
  stage: retrain
  script:
    - python model/train.py
    - docker build -t registry.gitlab.com/username/aiops-quality-project:retrain .
    - docker push registry.gitlab.com/username/aiops-quality-project:retrain
  when: manual

deploy:
  stage: deploy
  script:
    - kubectl apply -f argocd/application.yaml
