apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: mlops
type: Opaque
stringData:
  MLFLOW_S3_ENDPOINT_URL: http://minio.mlops.svc.cluster.local:9000
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  MLFLOW_TRACKING_URI: http://mlflow.mlops.svc.cluster.local:5000
  POSTGRES_URI: postgresql://mlflow:mlflow123@postgres.mlops.svc.cluster.local:5432/mlflow
