FROM python:3.9

WORKDIR /app

RUN apt update && apt install -y libgl1-mesa-glx

COPY model.pt inference.py imagenet_classes.json ./

RUN pip install torch torchvision pillow

CMD ["python", "inference.py", "example.jpg"]
