FROM python:3.9 as builder

WORKDIR /app
COPY model.pt inference.py imagenet_classes.json ./
RUN pip install --target=/app/torch_env torch torchvision pillow

FROM python:3.9-slim

WORKDIR /app
COPY --from=builder /app /app

ENV PYTHONPATH=/app/torch_env
CMD ["python", "inference.py", "example.jpg"]
